version: '3.8'

services:
  app:
    container_name: node_app
    image: nksingh1112/shorturl-app:1.0
    build: .
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    container_name: mongo_db
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: redis_cache
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: